services:
  # 1. PostgreSQL Database (Render Managed)
  - type: postgres
    name: voting-db
    databaseName: ${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    plan: free

  # 2. Web Service (Django App)
  - type: web
    name: alx-project-nexus
    env: python
    pythonVersion: "3.12"
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
      python manage.py create_superuser --username wuor --password 1234 --email admin@alx-project-nexus.com --force
    startCommand: gunicorn alx-project-nexus.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: voting-db
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "alx-project-nexus-yyh0.onrender.com,.onrender.com"
      - key: DB_NAME
        value: ${DB_NAME}
      - key: DB_USER
        value: ${DB_USER}
      - key: DB_PASSWORD
        value: ${DB_PASSWORD}
      - key: CORS_ALLOWED_ORIGINS
        value: "https://alx-project-nexus-yyh0.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://alx-project-nexus-yyh0.onrender.com"
    plan: free
