services:
  # 1. PostgreSQL Database (Render Managed)
  - type: postgres
    name: voting-db
    databaseName: voting_system_13u3
    user: root
    password: bPK77YSN802xkukVYLiMdRtDAujTq9Az
    plan: free

  # 2. Web Service (Django App)
  - type: web
    name: alx-project-nexus
    env: python
    pythonVersion: "3.12"
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn voting_system.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromService:
          type: postgres
          name: voting-db
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,alx-project-nexus-yyh0.onrender.com"
    plan: free
