# Generated by Django 5.2.6 on 2025-09-17 03:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='poll',
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('voter', 'position')},
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
    ]
